# List hidden files
alias l.='ls -d .*'

# Easy ssh-ing
alias ssrwth='ssh -X koch@portal.physik.rwth-aachen.de'
alias sshome='ssh -X koch@lx3b93.physik.rwth-aachen.de'
alias ss08='ssh -X koch@lx3b08.physik.rwth-aachen.de'

alias tunnelhome='ssh -n -N -L 12322:lx3b93:22 koch@tunnel.physik.rwth-aachen.de'

# Pylab
alias pylab='ipython --pylab'

# git shortcuts
alias gits='git status'
alias gitd='git diff'
alias gita='git add'
alias gitc='git commit'
alias gitp='git push'

# date-order in gitk
alias gitk='gitk --date-order'

# Use vimx if possible
if which vimx >/dev/null 2>/dev/null
then
    alias vim='vimx -v'
fi
