# List hidden files
alias l.='ls -d .*'

# Easy ssh-ing
alias ssh='ssh -X'

# Pylab
alias pylab='ipython --pylab'

# git shortcuts
alias gits='git status'
alias gitd='git diff'
alias gita='git add'
alias gitc='git commit'
alias gitp='git push'

# date-order in gitk
alias gitk='gitk --date-order'

# Use vimx if possible
if which vimx >/dev/null 2>/dev/null
then
    alias vim='vimx -v'
fi
