# List hidden files
alias l.='ls -d .*'

# Easy ssh-ing
alias ssrwth='ssh -X koch@portal.physik.rwth-aachen.de'
alias sshome='ssh -X koch@lx3b93.physik.rwth-aachen.de'
alias ss08='ssh -X koch@lx3b08.physik.rwth-aachen.de'

# Pylab
alias pylab='ipython --pylab'

# git shortcuts
alias gits='git status'
alias gitd='git diff'
alias gita='git add'
alias gitc='git commit'
alias gitp='git push'
