" Spaces insted of tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set autoindent

" Easy change of tab lengths
nnoremap ,2 :set ts=2 sts=2 sw=2<CR>
nnoremap ,4 :set ts=4 sts=4 sw=4<CR>
nnoremap ,8 :set ts=8 sts=8 sw=8<CR>

" Highlight trailing whitespaces
:highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen
:match ExtraWhitespace /\s\+$/

" Easy change of directory
nnoremap ,cd :cd %:p:h<CR>:pwd<CR>

"  , -> .
nnoremap ,. :inoremap , .<CR>
nnoremap ,, :iunmap ,<CR>

" display line numbers
set number

" highlight search
set hlsearch

" maximize current buffer
nnoremap <C-W># <C-W>_<C-W>\|

" Open a terminal in the current buffer (needs ConqueTerm)
nnoremap ,t :ConqueTerm bash<CR>
let g:ConqueTerm_ReadUnfocused = 1
let g:ConqueTerm_CWInsert = 1
let g:ConqueTerm_InsertOnEnter = 1
" or in a new split buffer
nnoremap <C-W>S :ConqueTermSplit bash<CR>
nnoremap <C-W>V :ConqueTermVSplit bash<CR>

" Enable mouse support
set mouse=a
