" Spaces instead of tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
autocmd FileType make setlocal noexpandtab "Makefiles NEED tabs
set autoindent

" Do not use two spaces after periods when formating text
:set nojoinspaces

" Easy change of tab lengths
nnoremap ,2 :set ts=2 sts=2 sw=2<CR>
nnoremap ,4 :set ts=4 sts=4 sw=4<CR>
nnoremap ,8 :set ts=8 sts=8 sw=8<CR>

" Highlight trailing whitespaces
autocmd ColorScheme * highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen
highlight ExtraWhitespace ctermbg=darkgreen guibg=lightgreen
autocmd WinEnter * match ExtraWhitespace /\s\+$/
match ExtraWhitespace /\s\+$/

" Change FG color for highlighted spelling errors to black in terminal
highlight SpellBad ctermfg=000

" No error marking of _ and ^ in markdown tex formulas
highlight link texOnlyMath Normal

" Easy change of directory
nnoremap ,cd :cd %:p:h<CR>:pwd<CR>

" Copy file path to clipboard
nnoremap ,cp :let @+ = expand("%:p")<CR>
" Copy file name to clipboard
nnoremap ,cf :let @+ = expand("%:t")<CR>

" Make tab completion more like in the shell
set wildmode=longest,list,full
set wildmenu

"  , -> .
nnoremap ,. :inoremap , .<CR>
nnoremap ,, :iunmap ,<CR>

" Enable syntax highlighting
syntax on

" display line numbers
set number

" highlight search
set hlsearch

" maximize current buffer
nnoremap <C-W># <C-W>_<C-W>\|

" Open a terminal in the current buffer (needs ConqueTerm)
nnoremap ,t :ConqueTerm bash<CR>
let g:ConqueTerm_ReadUnfocused = 1
let g:ConqueTerm_CWInsert = 1
let g:ConqueTerm_InsertOnEnter = 1
" or in a new split buffer
nnoremap <C-W>S :ConqueTermSplit bash<CR>
nnoremap <C-W>V :ConqueTermVSplit bash<CR>

" Enable mouse support
set mouse=a

" Do not auto-fold everything
set foldlevel=100

" Markdown support
" Use Latex math syntax highlighting
let g:vim_markdown_math = 1
