---
- hosts: localhost
  become: no
  tasks:
    - name: Create Terminator config dir
      file:
        path: ~/.config/terminator/
        state: directory
    - name: Copy Terminator config file
      copy:
        src: terminator-config.txt
        dest: ~/.config/terminator/config
