---
- hosts: localhost
  become: no
  tasks:
    - copy:
        src: gitignore.txt
        dest: ~/.gitignore
    - git_config:
        name: core.excludesfile
        scope: global
        value: ~/.gitignore
